# Generated by Django 5.0.6 on 2024-07-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("primary_food_group", models.CharField(max_length=100)),
                ("secondary_food_group", models.CharField(max_length=100)),
                (
                    "type_of_meal",
                    models.CharField(
                        choices=[
                            ("B", "Breakfast"),
                            ("L", "Lunch"),
                            ("D", "Dinner"),
                            ("S", "Snack"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
